
brews:
  - name: vault-sync
    builds:
      - ldflags:
      - -s -w -X "main.githubSHA={{.Env.GITHUB_SHA}} -X "main.githubRef={{.Env.GITHUB_REF}}"
    github:
      owner: rca0
      name: homebrew-tap
    homepage: https://github.com/rca0/vault-sync
    description: CLI to synchronize data from vault (hashicorp)
    folder: Formula
    test: |
      system "#{bin}/vault-sync -h"
